### ISSUE TITLE
Unhandled rejection Error: self signed certificate

### ISSUE THREAD

**Issue by marr** [ory/hydra-consent-app-express#3]
Hi,
I am trying to set this project up with a dockerized container running hydra. I get the following error after setting the `HYDRA_URL`, `HYDRA_CLIENT_ID`, and `HYDRA_CLIENT_SECRET` variables and running `npm start`:

> Unhandled rejection Error: self signed certificate
>     at TLSSocket.<anonymous> (_tls_wrap.js:1108:38)
>     at emitNone (events.js:105:13)
>     at TLSSocket.emit (events.js:207:7)
>     at TLSSocket._finishInit (_tls_wrap.js:638:8)
>     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:468:38)
> 

Thanks for any help

**Comment by aeneasr** [comment]
Try setting 

NODE_TLS_REJECT_UNAUTHORIZED=0
