### ISSUE TITLE
README

### ISSUE THREAD

**Issue by mewalig** [ory/hydra-consent-app-express#6]
Can anyone add at least something to the README here? Like, how to get started? what this does? Why this is awesome?

**Comment by aeneasr** [comment]
I have to lower your expectations here: this is just a placeholder/demo for hydra's docker compose demo file. Some documentation on how it is done is found in the code.

Would still need a short note explaining this.

**Comment by aeneasr** [comment]
Added some docs, hope this explains it better. If not feel free to PR or reopen.

**Comment by mewalig** [comment]
Thank you, that little bit is nonetheless very helpful!

**Comment by aeneasr** [comment]
Perfect
